apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-platform.fullname" . }}
  labels:
    {{- include "api-platform.labelsPWA" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api-platform.selectorLabelsPWA" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api-platform.selectorLabelsPWA" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "api-platform.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-pwa
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.pwa.image.image }}:{{ .Values.pwa.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.pwa.image.pullPolicy }}
          env:
            - name: NEXT_PUBLIC_ENTRYPOINT
              valueFrom:
                configMapKeyRef:
                  key: gateway-location
                  name: {{ include "api-platform.fullname" . }}
            - name: NEXT_PUBLIC_ME_URL
              valueFrom:
                  configMapKeyRef:
                      key: me-url
                      name: {{ include "api-platform.fullname" . }}
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                  configMapKeyRef:
                      key: api-url
                      name: {{ include "api-platform.fullname" . }}
            - name: NEXT_PUBLIC_BASE_URL
              valueFrom:
                  configMapKeyRef:
                      key: base-url
                      name: {{ include "api-platform.fullname" . }}
            - name: NEXT_PUBLIC_FRONTEND_URL
              valueFrom:
                  configMapKeyRef:
                      key: frontend-url
                      name: {{ include "api-platform.fullname" . }}
            - name: NEXT_PUBLIC_ORGANIZATION
              valueFrom:
                  configMapKeyRef:
                      key: organization
                      name: {{ include "api-platform.fullname" . }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
