apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-10-22T14:59:47.7160892+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: 14547289cad3050e7494f8d82807fe4d816b0025ae9708082da4017f8cf3b6c1
    name: commonground-gateway
    type: application
    urls:
    - charts/commonground-gateway-0.1.3.tgz
    version: 0.1.3
  pwa-verhuizen-s-hertogenbosch:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-10-22T14:59:47.6956561+02:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/master/api/helm/
      version: 0.1.3
    description: A Helm chart for the Verhuizen PWA of 's-Hertogenbosch
    digest: 0273fbffe9d9091e5bc0e22f96b97def6f9da81b29415d0e5fadeb9075d5db19
    name: pwa-verhuizen-s-hertogenbosch
    type: application
    urls:
    - pwa-verhuizen-s-hertogenbosch-0.1.0.tgz
    version: 0.1.0
generated: "2021-10-22T14:59:47.6729831+02:00"
