apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-10-19T12:48:43.0578165+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: edbb7b5c9fbd24bfe9ed5159d67af1e5af9aa1da4b009f99768d60c92db1dab3
    name: commonground-gateway
    type: application
    urls:
    - charts/commonground-gateway-0.1.2.tgz
    version: 0.1.2
  pwa-verhuizen-s-hertogenbosch:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-10-19T12:48:43.0418175+02:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/master/api/helm/
      version: 0.1.2
    description: A Helm chart for the Verhuizen PWA of 's-Hertogenbosch
    digest: ad558fe02a6eab5ee2124d2a029da2475f4d382e3bb170154ef4da76b93c7ec2
    name: pwa-verhuizen-s-hertogenbosch
    type: application
    urls:
    - pwa-verhuizen-s-hertogenbosch-0.1.0.tgz
    version: 0.1.0
generated: "2021-10-19T12:48:43.0253054+02:00"
