apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-10-19T13:44:15.6827182+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: edbb7b5c9fbd24bfe9ed5159d67af1e5af9aa1da4b009f99768d60c92db1dab3
    name: commonground-gateway
    type: application
    urls:
    - charts/commonground-gateway-0.1.2.tgz
    version: 0.1.2
  pwa-verhuizen-s-hertogenbosch:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2021-10-19T13:44:15.6687167+02:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/master/api/helm/
      version: 0.1.2
    description: A Helm chart for the Verhuizen PWA of 's-Hertogenbosch
    digest: 0663fd9ca62e0c3db01595269ba146a522d489350e3a3e3e1425b70ab635f3a7
    name: pwa-verhuizen-s-hertogenbosch
    type: application
    urls:
    - pwa-verhuizen-s-hertogenbosch-0.1.0.tgz
    version: 0.1.0
generated: "2021-10-19T13:44:15.6487172+02:00"
